# Generated by Django 5.0.6 on 2024-06-05 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('parent_category_id', models.CharField(blank=True, max_length=20, null=True)),
                ('category_type', models.CharField(max_length=20)),
                ('url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
